<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <eClassifiers xsi:type="ecore:EClass" name="AgreementModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//Role" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleType" eType="#//RoleType"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Role">
    <eLiterals name="PROVIDER"/>
    <eLiterals name="CONSUMER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RoleType">
    <eLiterals name="INITITATOR"/>
    <eLiterals name="RESPONDER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Datatype">
    <eLiterals name="INTEGER"/>
    <eLiterals name="FLOAT" value="1"/>
    <eLiterals name="NATURAL" value="2"/>
    <eLiterals name="NUMBER" value="3"/>
    <eLiterals name="BOOLEAN" value="4"/>
    <eLiterals name="SET" value="5"/>
    <eLiterals name="ENUM" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" lowerBound="1" eType="#//Range"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" lowerBound="1" eType="#//Enumerated"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Range">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumerated">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
