<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <eClassifiers xsi:type="ecore:EClass" name="AgreementModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" lowerBound="1" eType="#//Context"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" lowerBound="1" eType="#//AgreementTerm"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initiator" eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responder" eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metrics">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" eType="#//Metric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//Role" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleType" eType="#//RoleType"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Role">
    <eLiterals name="PROVIDER"/>
    <eLiterals name="CONSUMER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RoleType">
    <eLiterals name="INITITATOR"/>
    <eLiterals name="RESPONDER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Datatype">
    <eLiterals name="INTEGER"/>
    <eLiterals name="FLOAT" value="1"/>
    <eLiterals name="NATURAL" value="2"/>
    <eLiterals name="NUMBER" value="3"/>
    <eLiterals name="BOOLEAN" value="4"/>
    <eLiterals name="SET" value="5"/>
    <eLiterals name="ENUM" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Datatype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" eType="#//Domain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" abstract="true" eSuperTypes="#//Range #//Enumerated"/>
  <eClassifiers xsi:type="ecore:EClass" name="Range">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumerated">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgreementTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" eType="#//ServiceConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitorableProperties"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guaranteeTerms" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpointReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definitionReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitorReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="features" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configurationProperties"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuaranteeTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slo" eType="#//SLO"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qc" eType="#//QualifyingCondition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compensations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metric" eType="#//Metric"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#//Scope"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definitionReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationProperty">
    <eAnnotations/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonitorableProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitorReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SLO">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Scope">
    <eLiterals name="GLOBAL"/>
    <eLiterals name="LOCAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compensation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" eType="#//AssessmentInterval"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CompensationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifyingCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompensationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssessmentInterval">
    <eLiterals name="YEARLY"/>
    <eLiterals name="MONTHLY" value="1"/>
    <eLiterals name="WEEKLY" value="2"/>
    <eLiterals name="DAILY" value="3"/>
    <eLiterals name="HOURLY" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompensationType">
    <eLiterals name="PENALTY"/>
    <eLiterals name="REWARD" value="1"/>
  </eClassifiers>
</ecore:EPackage>
