<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AgreementMetamodel" nsURI="http://agreement.metamodel/1.0" nsPrefix="mmag">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgreementModel">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//Context" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agTerm" lowerBound="1"
        eType="#//AgreementTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eAnnotations source="gmf.node">
      <details key="label.placement" value="none"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Context"/>
      <details key="tool.description" value="Creates a new context section"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" lowerBound="1"
        upperBound="2" eType="#//Actor" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" upperBound="-1"
        eType="#//Metric" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor">
    <eAnnotations source="gmf.node">
      <details key="label" value="id"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Actor"/>
      <details key="tool.description" value="Creates a new actor"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//Role" defaultValueLiteral="PROVIDER"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleType" eType="#//RoleType"
        defaultValueLiteral="RESPONDER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Role">
    <eLiterals name="PROVIDER"/>
    <eLiterals name="CONSUMER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RoleType">
    <eLiterals name="INITITATOR"/>
    <eLiterals name="RESPONDER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Datatype">
    <eLiterals name="INTEGER"/>
    <eLiterals name="FLOAT" value="1"/>
    <eLiterals name="NATURAL" value="2"/>
    <eLiterals name="NUMBER" value="3"/>
    <eLiterals name="BOOLEAN" value="4"/>
    <eLiterals name="SET" value="5"/>
    <eLiterals name="ENUM" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric">
    <eAnnotations source="gmf.node">
      <details key="label" value="id"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Metric"/>
      <details key="tool.description" value="Creates a new metric"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Datatype"
        defaultValueLiteral="INTEGER"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//Domain" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Range" eSuperTypes="#//Domain">
    <eAnnotations source="gmf.node">
      <details key="label" value="min,max"/>
      <details key="label.pattern" value="[{0}..{1}]"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Range"/>
      <details key="tool.description" value="Creates a range domain"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="100"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumerated" eSuperTypes="#//Domain">
    <eAnnotations source="gmf.node">
      <details key="label.placement" value="none"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Enumerated"/>
      <details key="tool.description" value="Creates an enumerated domain"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//Value" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgreementTerm">
    <eAnnotations source="gmf.node">
      <details key="label.placement" value="none"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Agreement Term"/>
      <details key="tool.description" value="Creates an agreement terms section"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceConfigurarion" lowerBound="1"
        eType="#//ServiceConfiguration" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitorableProperties"
        upperBound="-1" eType="#//MonitorableProperty" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guaranteeTerms" upperBound="-1"
        eType="#//GuaranteeTerm" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceConfiguration">
    <eAnnotations source="gmf.node">
      <details key="label" value="serviceName"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Service Configuration"/>
      <details key="tool.description" value="Creates a service configuration section"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpointReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definitionReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitorReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurationProperties"
        upperBound="-1" eType="#//ConfigurationProperty" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuaranteeTerm">
    <eAnnotations source="gmf.node">
      <details key="label" value="id,role"/>
      <details key="label.pattern" value="{0} - {1}"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Guarantee Term"/>
      <details key="tool.description" value="Creates a new guarantee term"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//Role" defaultValueLiteral="PROVIDER"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slo" lowerBound="1" eType="#//SLO"
        containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifyingCondition" eType="#//QualifyingCondition"
        containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compensations" upperBound="-1"
        eType="#//Compensation" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eAnnotations source="gmf.node">
      <details key="label" value="id"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Feature"/>
      <details key="tool.description" value="Creates a new feature"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#//Scope"
        defaultValueLiteral="GLOBAL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definitionReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="#//Feature">
      <eAnnotations source="gmf.link"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric" eType="#//Metric">
      <eAnnotations source="gmf.link"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationProperty" eSuperTypes="#//Property">
    <eAnnotations source="gmf.node">
      <details key="label" value="id"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Configuration Property"/>
      <details key="tool.description" value="Creates a new configuration property"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonitorableProperty" eSuperTypes="#//Property">
    <eAnnotations source="gmf.node">
      <details key="label" value="id"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Monitorable Property"/>
      <details key="tool.description" value="Creates a new monitorable property"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitorReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SLO">
    <eAnnotations source="gmf.node">
      <details key="label" value="expression"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="SLO"/>
      <details key="tool.description" value="Creates a new service level objective"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Scope">
    <eLiterals name="GLOBAL"/>
    <eLiterals name="LOCAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compensation">
    <eAnnotations source="gmf.node">
      <details key="label" value="interval,type"/>
      <details key="label.pattern" value="with {0} {1}"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Compensation"/>
      <details key="tool.description" value="Creates a new compensation"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" eType="#//AssessmentInterval"
        defaultValueLiteral="MONTHLY"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CompensationType"
        defaultValueLiteral="REWARD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compensationElements" upperBound="-1"
        eType="#//CompensationElement" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifyingCondition">
    <eAnnotations source="gmf.node">
      <details key="label" value="expression"/>
      <details key="label.pattern" value="onlyIf({0})"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Qualifying Condition"/>
      <details key="tool.description" value="Creates a new qualifying condition"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompensationElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="expression,condition"/>
      <details key="label.pattern" value="of {1} if {0}"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Compensation Element"/>
      <details key="tool.description" value="Creates a new compensation element"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssessmentInterval">
    <eLiterals name="YEARLY"/>
    <eLiterals name="MONTHLY" value="1"/>
    <eLiterals name="WEEKLY" value="2"/>
    <eLiterals name="DAILY" value="3"/>
    <eLiterals name="HOURLY" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompensationType">
    <eLiterals name="PENALTY"/>
    <eLiterals name="REWARD" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Parameter"/>
      <details key="tool.description" value="Creates a new parameter"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eAnnotations source="gmf.node">
      <details key="label" value="id"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="tool.name" value="Value"/>
      <details key="tool.description" value="Creates a new value"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
